import React from 'react';
import { Info } from 'lucide-react';

export const DEFAULT_DISCLAIMER =
  'Generated by an automated quantitative model for research and education only. Not investment advice or a recommendation to buy or sell any security. Consult a SEBI-registered investment adviser before investing.';

export const BACKTEST_DISCLAIMER =
  'Backtested results are hypothetical and simulated with the assumptions shown. Past performance, real or simulated, does not guarantee future returns. Not investment advice.';

interface DisclaimerProps {
  children?: React.ReactNode;
  className?: string;
}

/** Small, consistent "not investment advice" notice for anywhere the app shows buy/sell signals. */
export const Disclaimer: React.FC<DisclaimerProps> = ({ children, className = '' }) => (
  <p className={`flex items-start gap-1.5 text-[10px] font-mono text-textMuted leading-relaxed ${className}`}>
    <Info className="w-3 h-3 mt-0.5 shrink-0" aria-hidden="true" />
    <span>{children ?? DEFAULT_DISCLAIMER}</span>
  </p>
);
