from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from analysis.models.patterns import PatternDetection
from analysis.models.levels import SupportResistanceLevel
from analysis.support_resistance import SRZone
from analysis.models.market import MarketContextModel
from analysis.models.scores import TechnicalScores
from analysis.models.chart import ChartDataModel
from analysis.models.risk import RiskProfile
from intelligence.schemas import AIResearchReportModel

class DeterministicAnalysisReport(BaseModel):
    """
    Complete JSON schema representing the outputs of the deterministic Analysis Engine.
    This model serves as the boundary between the Analysis Engine and the Intelligence Engine.
    """
    ticker: str
    company_name: str
    analysis_date: str
    market_context: MarketContextModel
    scores: TechnicalScores
    risk_profile: RiskProfile
    positive_factors: List[str]
    negative_factors: List[str]
    neutral_factors: List[str]
    chart_data: ChartDataModel
    patterns: List[PatternDetection]
    support_zones: List[SRZone]
    resistance_zones: List[SRZone]
    ai_research_report: Optional[AIResearchReportModel] = Field(default=None, description="Generated AI Analyst Research Report")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Execution timing and metadata")


class FinalResearchReport(BaseModel):
    """
    Final Output JSON schema populated by both Analysis and Intelligence engines.
    """
    ticker: str
    company: str
    analysis_date: str
    overall_score: float
    recommendation: str
    confidence: float
    risk_level: str
    trend: str
    trend_strength: str
    buy_probability: float
    technical_summary: str = Field(..., description="Generated by LLM: Summary of technical metrics")
    strengths: List[str] = Field(..., description="Generated by LLM: List of technical strengths")
    weaknesses: List[str] = Field(..., description="Generated by LLM: List of technical weaknesses")
    bull_case: str = Field(..., description="Generated by LLM: Detailed bull case")
    bear_case: str = Field(..., description="Generated by LLM: Detailed bear case")
    support_levels: List[float]
    resistance_levels: List[float]
    detected_patterns: List[str] = Field(..., description="Summarized names of patterns")
    indicator_summary: Dict[str, Any]
    short_term_outlook: str = Field(..., description="Generated by LLM: 1M - 3M outlook")
    medium_term_outlook: str = Field(..., description="Generated by LLM: 3M - 6M outlook")
    key_risks: List[str] = Field(..., description="Generated by LLM: Critical risk highlights")
    summary: str = Field(..., description="Generated by LLM: Concluding research remarks")
